### PR TITLE
Issue/4 create session app

### LINKED ISSUE #4: session appの作成
# 概要

セッション管理用のアプリを作成。

# 改善の背景

# 要件

# 検討事項

- ~~ログイン実装（google, twitter, github, facebook, email, e.t.c）~~

# 実装方針

- google認証まわりはfirebase

# テスト項目

- [ ]

### PR DESCRIPTION
**Pull request by kathmandu777**
# 概要

firebase authの基盤実装

# 対応するIssue

close #4 

# 修正内容の確認方法

1. temp-index へアクセス
2. sign in 
3. temp-index へリダイレクトされる
4. サインイン情報が正しいことを確認。（emailとusernameが表示されるはず）
5. sign out
6. サインイン情報が何も表示されていないことを確認

# レビューのポイント

### CODE REVIEW

**Comment by kathmandu777** [comment]
マージはこちらで行います(conflict発生しているので)。レビュー後slackでメンション飛ばしてください。

**Review by lemonadern — COMMENTED** [review]
In my environment, the process stops in the middle of sign-in process.
It doesn't redirect to `/temp-index` .

Do you have any solutions? I want you to check it out.

**Comment by kathmandu777** [comment]
> In my environment, the process stops in the middle of sign-in process.
> It doesn't redirect to `/temp-index` .
> 
> Do you have any solutions? I want you to check it out.

is there this statement `postgres_1  | 2021-08-08 13:37:42.046 UTC [38] ERROR:  duplicate key value violates unique constraint "account_user_email_key"` in the logs?
if so, delete that user, and then retry to  sign in.
if not, there must be some kind of error. I want you to find that. the logs is located `/var/log/django.log` in django container.

(I deleted your account from firebase. so you can try from first completely.)

**Comment by lemonadern** [comment]
@kathmandu777 
I checked the logs. Internal Server Error or Attribute Error was happened there.
```
Internal Server Error: /signin-callback
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./session/views.py", line 12, in signin_callback
    user = authenticate(request)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/debug.py", line 42, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/__init__.py", line 68, in authenticate
    for backend, backend_path in _get_backends(return_tuples=True):
  File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/__init__.py", line 27, in _get_backends
    backend = load_backend(backend_path)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/__init__.py", line 21, in load_backend
    return import_string(path)()
  File "/usr/local/lib/python3.8/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./session/backends.py", line 3, in <module>
    from .firebase import *
  File "./session/firebase.py", line 10, in <module>
    "private_key": os.environ.get('FIREBASE_PRIVATE_KEY').replace('\\n', '\n'),
AttributeError: 'NoneType' object has no attribute 'replace'
```

**Comment by lemonadern** [comment]
@kathmandu777 
OH, I think it needs the FIREBASE PRIBATE KEY int the .env

**Comment by kathmandu777** [comment]
rebased.
so, confilcts are resolved.

**Comment by lemonadern** [comment]
@kathmandu777 
I got this error.
```
postgres_1  | 2021-08-09 09:46:43.955 UTC [34] ERROR:  column account_user.uid does not exist at character 169
postgres_1  | 2021-08-09 09:46:43.955 UTC [34] HINT:  Perhaps you meant to reference the column "account_user.id" or the column "account_user.uuid".
postgres_1  | 2021-08-09 09:46:43.955 UTC [34] STATEMENT:  SELECT "account_user"."password", "account_user"."last_login", "account_user"."is_superuser", "account_user"."uuid", "account_user"."email", "account_user"."username", "account_user"."uid", "account_user"."is_active", "account_user"."is_admin", "account_user"."date_joined" FROM "account_user" WHERE ("account_user"."email" = '******************@gmail.com' AND "account_user"."uid" = '***********************' AND "account_user"."username" = '*****************') LIMIT 21
```
I tried migrating in the django container. but nothing have changed.
Do I have to add `account_user.uid` column to the database? What do you think?

**Comment by kathmandu777** [comment]
@lemonadern 

due to change of primary key field.
so, please delete db completely. then rerty.

### command to delete db
in postgres container
`delete from account_user;` 
 
if above command dosent work, try this.
`docker-compose down -v`

**Review by lemonadern — APPROVED** [review]
I deleted volumes and then tried it, it worked.

**Pull request merged**
